# Woodpecker CI configuration
# Calls the same build script as GitHub Actions

steps:
  - name: build-15-latest
    image: /bin/sh
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      GITHUB_ACTOR:
        from_secret: GITHUB_USER
    commands:
      - |
        # Download shared build script (pinned to version)
        mkdir -p scripts
        fetch -qo scripts/build-base.sh \
          "https://raw.githubusercontent.com/daemonless/daemonless/build-base-v1.0.0/scripts/build-base.sh"
        chmod +x scripts/build-base.sh

        ./scripts/build-base.sh \
          --doas \
          --registry ghcr.io \
          --image ghcr.io/daemonless/base \
          --freebsd-version 15 \
          --pkg-branch latest \
          --push-latest \
          --login --push

  - name: build-15-quarterly
    image: /bin/sh
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      GITHUB_ACTOR:
        from_secret: GITHUB_USER
    commands:
      - |
        # Download shared build script (pinned to version)
        mkdir -p scripts
        fetch -qo scripts/build-base.sh \
          "https://raw.githubusercontent.com/daemonless/daemonless/build-base-v1.0.0/scripts/build-base.sh"
        chmod +x scripts/build-base.sh

        ./scripts/build-base.sh \
          --doas \
          --registry ghcr.io \
          --image ghcr.io/daemonless/base \
          --freebsd-version 15 \
          --pkg-branch quarterly \
          --login --push

when:
  - event: push
    branch: main
    path:
      exclude: [ "*.md", "docs/**", "LICENSE", ".gitignore" ]
  - event: manual
