# --------------------------------------------------------------------------
# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
#
# Source: Containerfile.j2
# --------------------------------------------------------------------------

ARG BASE_VERSION=15-pkg
FROM ghcr.io/daemonless/base-core:${BASE_VERSION}

ARG PACKAGES="s6 s6-rc execline"
ARG VERSION=""

LABEL org.opencontainers.image.title="FreeBSD Base" \
    org.opencontainers.image.description="FreeBSD base image with s6 supervision" \
    org.opencontainers.image.source="https://github.com/daemonless/base" \
    org.opencontainers.image.url="https://github.com/daemonless/base" \
    org.opencontainers.image.licenses="" \
    org.opencontainers.image.vendor="daemonless" \
    org.opencontainers.image.authors="daemonless" \
    io.daemonless.type="base" \
    io.daemonless.category="Base" \
    io.daemonless.packages="${PACKAGES}"

COPY root/ /

RUN pkg update && \
    pkg install -y ${PACKAGES} && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

RUN mkdir -p /etc/cont-init.d \
    /etc/services.d \
    /custom-cont-init.d \
    /custom-services.d \
    /run/s6/services

RUN chmod +x /init /healthz /etc/cont-init.d/* 2>/dev/null || true

ENTRYPOINT ["/init"]