ARG FREEBSD_RELEASE=15.0
FROM ghcr.io/freebsd/freebsd-runtime:${FREEBSD_RELEASE}

ARG FREEBSD_MAJOR=15
ARG FREEBSD_ARCH=amd64
ARG PKG_BRANCH=quarterly
ARG PACKAGES="s6 s6-rc execline FreeBSD-utilities jq"
ARG VERSION=""

LABEL org.opencontainers.image.title="{{ title }}" \
    org.opencontainers.image.description="{{ description }}" \
    org.opencontainers.image.source="{{ repo_url }}" \
    org.opencontainers.image.url="{{ repo_url }}" \
    org.opencontainers.image.licenses="{{ license }}" \
    org.opencontainers.image.vendor="daemonless" \
    org.opencontainers.image.authors="daemonless" \
    io.daemonless.type="base" \
    io.daemonless.category="{{ category }}" \
    io.daemonless.packages="${PACKAGES}"

ENV ASSUME_ALWAYS_YES=yes
ENV PUID=1000
ENV PGID=1000
ENV TZ=UTC

COPY root/ /

RUN mkdir -p /etc/pkg && \
    printf '%s\n' \
      'FreeBSD-ports: { enabled: no }' \
      'FreeBSD-ports-kmods: { enabled: no }' \
      'FreeBSD-base: {' \
      '  url: "http://pkg.FreeBSD.org/${ABI}/base_release_${VERSION_MINOR}",' \
      '  mirror_type: "NONE",' \
      '  enabled: yes' \
      '}' \
      'Ports: {' \
      "  url: \"http://pkg.FreeBSD.org/FreeBSD:${FREEBSD_MAJOR}:${FREEBSD_ARCH}/${PKG_BRANCH}\"," \
      '  mirror_type: "NONE",' \
      '  enabled: yes' \
      '}' > /etc/pkg/FreeBSD.conf

RUN rm -rf /usr/local/etc/pkg/repos && \
    pkg update && \
    pkg install -y ${PACKAGES} && \
    chmod 755 /usr/local/sbin && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

RUN pw groupadd -n bsd -g 1000 && \
    pw useradd -n bsd -u 1000 -g bsd -d /config -s /bin/sh -c "Container User"

RUN mkdir -p /etc/cont-init.d \
    /etc/services.d \
    /custom-cont-init.d \
    /custom-services.d \
    /run/s6/services

RUN chmod +x /init /healthz /etc/cont-init.d/* 2>/dev/null || true

ENTRYPOINT ["/init"]
