ARG BASE_VERSION=15-pkg
FROM ghcr.io/daemonless/base-core:${BASE_VERSION}

ARG PACKAGES="s6"
ARG VERSION=""

LABEL org.opencontainers.image.title="{{ title }}" \
    org.opencontainers.image.description="{{ description }}" \
    org.opencontainers.image.source="{{ repo_url }}" \
    org.opencontainers.image.url="{{ repo_url }}" \
    org.opencontainers.image.licenses="{{ license }}" \
    org.opencontainers.image.vendor="daemonless" \
    org.opencontainers.image.authors="daemonless" \
    io.daemonless.type="base" \
    io.daemonless.category="{{ category }}" \
    io.daemonless.packages="${PACKAGES}"

COPY root/ /

RUN pkg update && \
    pkg install -y ${PACKAGES} && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

RUN mkdir -p /etc/cont-init.d \
    /etc/services.d \
    /custom-cont-init.d \
    /custom-services.d \
    /run/s6/services

RUN chmod +x /init /healthz /etc/cont-init.d/* 2>/dev/null || true

ENTRYPOINT ["/init"]
