type: base
build:
  architectures:
    - amd64
  variants:
    - tag: "15.1"
      args:
        BASE_VERSION: "15.1-pkg"
      aliases: ["latest", "15-quarterly", "15"]
    - tag: "15.1-latest"
      args:
        BASE_VERSION: "15.1-pkg-latest"
      aliases: ["15-latest"]

cit:
  mode: shell
